version: '2'

services:
  web:
    command: bundle exec puma -w 1 -t 1:16
    container_name: redmine_web
    depends_on:
      - mysql
    environment:
      - VIRTUAL_HOST=redmine.local
      - VIRTUAL_PORT=9292
    expose:
      - "9292"
    image: my_redmine_development
    links:
      - "mysql:mysql"
    networks:
      - backend_network
      - frontend_network
    user: notroot
    volumes:
      - ../redmine:/work
      - ../secrets/:/secrets
    working_dir: /work
  mysql:
    container_name: redmine_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:5.7.16
    networks:
      - backend_network
    volumes:
      - ../import/:/import
      - mysql_data:/var/lib/mysql
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: redmine_nginx_proxy
    networks:
      - frontend_network
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  mysql_data:
    driver: local

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
